"""
Day 4 Penalty - Clean Template (No Solutions)

Purpose:
Reinforce Day 1-3 material without adding new concepts.
You must write the code yourself in this file.

Allowed tools:
- Variables
- int, float, str, bool, complex
- input()
- Arithmetic operators: + - * / // % **
- Comparison operators: < > ==
- Logical operators: and, not
- math.pi and math.sqrt
- print()

Target:
- Complete all 30 tasks
- Keep output clearly labeled
- Keep style consistent with Day 01-03 files

Declaration:
- The TODO/checklist structure in this file was generated by AI.
- The executable code in this file was completed by me.

Context:
- I could not complete Day 4 on time because of my poor planning skills.
- This file is basically a punishment for missing Day 4.
- After completing this penalty, I can move to Day 4 Training and Exercises.
"""

# TODO — Day 4 Exercises Overview
# [x] Exercise 1 — Create integer variable and print labeled value
# [x] Exercise 2 — Create float variable and print labeled value
# [x] Exercise 3 — Create string variable and print value
# [x] Exercise 4 — Create boolean variable and print value
# [x] Exercise 5 — Create complex variable and print value
# [x] Exercise 6 — Print type() of all five variables
# [x] Exercise 7 — Ask for whole number, convert with int(), print
# [x] Exercise 8 — Ask for second whole number, convert with int(), print
# [x] Exercise 9 — Ask for decimal number, convert with float(), print
# [x] Exercise 10 — Ask for text value and print
# [x] Exercise 11 — Demonstrate int(input()) conversion
# [x] Exercise 12 — Demonstrate float(input()) conversion
# [x] Exercise 13 — Add two numbers and print result
# [x] Exercise 14 — Subtract two numbers and print result
# [x] Exercise 15 — Multiply two numbers and print result
# [x] Exercise 16 — Divide two numbers and print result
# [x] Exercise 17 — Use exponentiation and print result
# [x] Exercise 18 — Use floor division and print result
# [x] Exercise 19 — Triangle area calculation (0.5 * base * height)
# [x] Exercise 20 — Rectangle area calculation (length * width)
# [x] Exercise 21 — Circle area calculation (math.pi * r**2)
# [x] Exercise 22 — Circle circumference calculation (2 * math.pi * r)
# [x] Exercise 23 — Compare two numbers with > or <
# [x] Exercise 24 — Compare two numbers with ==
# [x] Exercise 25 — Build boolean expression with and
# [x] Exercise 26 — Reverse boolean result using not
# [x] Exercise 27 — Print boolean results with labels
# [x] Exercise 28 — Check even number using modulo
# [x] Exercise 29 — Print even/odd using if/else
# [x] Exercise 30 — Slope and Euclidean distance from two points

# Day 4 Playground

# Exercises day 4

# 1. Create an integer variable and print it with a label
# 2. Create a float variable and print it with a label
# 3. Create a string variable and print it
# 4. Create a boolean variable and print it
# 5. Create a complex variable and print it
# 6. Print the type() of all five variables

# Variables and their values organized on top
import math


SA_Integer = 2
SA_Float = 4.4
SA_String = "String Value"
SA_Bool = True
SA_Complex = complex(2, 3)

# Type checks and value display
print("Section A - Variables and Data Types:")
print("_________________________________________________________")
print("| i | Variable   |  Type              | Value           |")                 
print("|___|____________|____________________|_________________|")
print("| 1 | SA_Integer | ", type(SA_Integer), "    | ", SA_Integer, "             |")
print("| 2 | SA_Float   | ", type(SA_Float),     "  | ", SA_Float, "           |")
print("| 3 | SA_String  | ", type(SA_String),  "    | ", SA_String, "  |")
print("| 4 | SA_Bool    | ", type(SA_Bool),     "   | ", SA_Bool, "          |")
print("| 5 | SA_Complex | ", type(SA_Complex),   "  | ", SA_Complex, "       |")
print("|___|____________|____________________|_________________|")

print("")
print("◆━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━◆")
print("")

# 7. Ask for a whole number, convert with int(), and print it
# 8. Ask for another whole number, convert with int(), and print it
# 9. Ask for a decimal number, convert with float(), and print it
# 10. Ask for a text value and print it
# 11. Demonstrate explicit int(input()) conversion and print result
# 12. Demonstrate explicit float(input()) conversion and print result

SB_Whole_Num01 = int(input("Please Entre the first whole number: "))
print("You entered number: ", SB_Whole_Num01)
print("")

SB_Whole_Num02 = int(input("Please Entre the Second whole number: "))
print("You entered number: ", SB_Whole_Num02)
print("")

SB_Decimal_Num = float(input("Please Entre a Decimal Number: "))
print("You entered number: ", SB_Decimal_Num)
print("")

SB_Text = input("Please write a sentence: ")
print("You entered number: ", SB_Text)

print("")
print("◆━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━◆")
print("")
# 13. Add two numbers and print labeled result
# 14. Subtract two numbers and print labeled result
# 15. Multiply two numbers and print labeled result
# 16. Divide two numbers and print labeled result
# 17. Use exponentiation (**) and print labeled result
# 18. Use floor division (//) and print labeled result

# Variables and their values organized on top
SC_Num_A, SC_Num_B, SC_Num_C = 2, 4, 8

# Arithmetic operations
print("We have 3 numbers (A, B, C) = (", SC_Num_A, SC_Num_B, SC_Num_C, ")" )
print("         Total: (A + B) = ", SC_Num_A + SC_Num_B)
print("          Diff: (B - C) = ", SC_Num_B - SC_Num_C)
print("       Product: (A * C) = ", SC_Num_A * SC_Num_C)
print("           Div: (C / A) = ", SC_Num_C / SC_Num_A)
print("Exponentiation: (C ^ B) = ", SC_Num_C ** SC_Num_B)
print("     Floor Div: (A // B)= ", SC_Num_A // SC_Num_B)

print("")
print("◆━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━◆")
print("")
# 19. Triangle area (area = 0.5 * base * height)
# 20. Rectangle area (area = length * width)
# 21. Circle area (area = math.pi * r**2)
# 22. Circle circumference (c = 2 * math.pi * r)

# Variables and their values organized on top
SD_Triangle_Base, SD_Triangle_Height    = 10, 20
SD_Rectangle_Length, SD_Rectangle_Width = 16, 9 
SD_Circle_Radius = 15

# Arithmetic operations
SD_Triangle_Area        = .5 * SD_Triangle_Base * SD_Triangle_Height
SD_Rectangle_Area       = SD_Rectangle_Length * SD_Rectangle_Width
SD_Circle_Area          = math.pi * SD_Circle_Radius**2
SD_Circle_Circumference = 2 * math.pi * SD_Circle_Radius

print("We have Triangle with the Area of ", SD_Triangle_Area)
print("We have Rectangle with the Area of ", SD_Rectangle_Area)
print("We have Circle with the Area of ", SD_Circle_Area)
print("The Circle's Circumference: ", SD_Circle_Circumference)

print("")
print("◆━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━◆")
print("")
# 23. Compare two numbers using > or < and print explanation
# 24. Compare two numbers using == and print explanation
# 25. Create one boolean expression with and
# 26. Reverse a boolean result using not
# 27. Print all boolean results with clear labels

# Variables and their values organized on top
SE_Num01 = 10
SE_Num02 = 20

# Boolean operations
SE_Smaller = SE_Num01 <  SE_Num02
SE_Equal  = SE_Num01 == SE_Num02
SE_False   = SE_Num02 and SE_Num01 == SE_Num01 + SE_Num02
SE_Not_False = not False

print("10 is smaller than 20? ", SE_Smaller)
print("10 is equal to 20?", SE_Equal)
print(" 10 and 20 are separately equal to 30?", SE_False)
print("What is the opposite of True?", SE_Not_False)


print("")
print("◆━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━◆")
print("")
# 28. Check if a number is even using n % 2 == 0
# 29. Use if/else to print "even" or "odd"

SF_Num = 9
SF_is_Even = (SF_Num % 2) == 0 

print("Is number", SF_Num, "Even?", SF_is_Even)

if (SF_is_Even):
    print(SF_Num, "Is Even")
else:
    print(SF_Num, "Is Odd")

print("")
print("◆━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━◆")
print("")
# 30. Option A — Slope
# Formula: (y2 - y1) / (x2 - x1)

SG_Point_01 = [10, 20]
SG_Point_02 = [-10, -20]

SG_DeltaX = SG_Point_01[0] - SG_Point_02[0]
SG_Deltay = SG_Point_01[1] - SG_Point_02[1]

SG_Slope = SG_Deltay / SG_DeltaX 

print("We have 2 points, point 1:", SG_Point_01, "And point 2:", SG_Point_02)

print("Slope is equal to: ", SG_Slope)

# 30. Option B — Euclidean Distance
# Formula: math.sqrt((x2 - x1)**2 + (y2 - y1)**2)

SG_Distance = math.sqrt(SG_DeltaX**2 + SG_Deltay**2)
print("Distance is equal to: ", SG_Slope)

# Completion proof

# [x] All 30 tasks completed
# [x] Script runs successfully
# [x] Output labels are clear and consistent

# Commit message to use when done:
# "Day 4 reinforcement completed"

# Commit hash:
# ______________________________


# Reflection (write your answer below)
# Note: The TODO checklist was generated by AI, but the code implementation was done by me.
# Why was Day 4 missed?
# I missed Day 4 in time because of poor planning skills.
# What structural change prevents it next time?
# This is my penalty for missing Day 4; after this, I move to Day 4 Training and Exercises.
